FROM node:20-alpine

WORKDIR /app

COPY ./application/package*.json ./

RUN npm install

COPY ../application ./
RUN echo "Testing GitHub Actions workflow sha" > /app/test.txt

EXPOSE 3000

CMD ["node", "index.js"]
