apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: app
spec:
  refreshInterval: 1h                  
  secretStoreRef:
    name: aws-secretsmanager         
    kind: SecretStore                 
  target:
    name: db-credentials              # Name of the Kubernetes Secret that will be created
    creationPolicy: Owner             # It manages the lifecycle of the secret
  data:
    - secretKey: username             # Key inside the k8s Secret
      remoteRef:
        key: my_SM_for_rds_eks         # The AWS Secrets Manager secret name or ARN
        property: username            # Property inside your AWS secret JSON
    - secretKey: password
      remoteRef:
        key: my_SM_for_rds_eks
        property: password
